### PR TITLE
AGENT-118: Unit tests for retrieving node0 IP

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
Ref: https://issues.redhat.com/browse/AGENT-118

### CODE REVIEW

**Comment by lranjbar** [comment]
It looks good so far. I think we should add a test case where the IP address is missing (nil).

```
[lranjbar@localhost fleeting]$ go test -v ./...
?   	github.com/openshift-agent-team/fleeting/cmd	[no test files]
?   	github.com/openshift-agent-team/fleeting/data	[no test files]
?   	github.com/openshift-agent-team/fleeting/pkg/imagebuilder	[no test files]
?   	github.com/openshift-agent-team/fleeting/pkg/isosource	[no test files]
=== RUN   TestGetNodeZeroIP
=== RUN   TestGetNodeZeroIP/Valid_NMStateConfig_with_only_one_IPV4_IP_address
=== RUN   TestGetNodeZeroIP/Valid_NMStateConfig_with_only_one_IPV6_IP_address
=== RUN   TestGetNodeZeroIP/Valid_NMStateConfig_with_multiple_interfaces
=== RUN   TestGetNodeZeroIP/Valid_NMStateConfig_with_multiple_IPV4_IP_addresses_in_a_single_interface
--- PASS: TestGetNodeZeroIP (0.00s)
    --- PASS: TestGetNodeZeroIP/Valid_NMStateConfig_with_only_one_IPV4_IP_address (0.00s)
    --- PASS: TestGetNodeZeroIP/Valid_NMStateConfig_with_only_one_IPV6_IP_address (0.00s)
    --- PASS: TestGetNodeZeroIP/Valid_NMStateConfig_with_multiple_interfaces (0.00s)
    --- PASS: TestGetNodeZeroIP/Valid_NMStateConfig_with_multiple_IPV4_IP_addresses_in_a_single_interface (0.00s)
PASS
ok  	github.com/openshift-agent-team/fleeting/pkg/manifests	0.007s
```

**Comment by pawanpinjarkar** [comment]
> It looks good so far. I think we should add a test case where the IP address is missing (nil).
> 
@lranjbar We are parsing the IP value [here](https://github.com/openshift-agent-team/fleeting/blob/main/pkg/manifests/nmstateconfig.go#L164-L167) which takes care if the value is missing or is really not an IP but any string. I think we should have separate code and tests to validate all the user inputs.

**Review by rwsu — CHANGES_REQUESTED** [review]
Shouldn't there be a Makefile target to run the unit test?

**Comment by pawanpinjarkar** [comment]
> Shouldn't there be a Makefile target to run the unit test?

Yes, added. @rwsu

**Comment by bfournie** [comment]
I think that eventually we should have a generic way to mock reading from a manifest file so we can have the static contents of these files in *_test.go files to test all of these manifest inputs, but until then
/lgtm

**Pull request merged**
